---
# common parameters

# root directory for docker structure
base_dir: "{{ playbook_dir }}/../"
# prefix for docker images
package_prefix: unsafeopenssl-pkg

# build macros

fail_build: 'echo "I failed :("; exit 1'

default_build_command: | 
  RUN ./build.sh && \
  echo Store distro for packager && \
  lsb_release -i | awk {'print $3'} > /build/distro && \
  echo Store distro version for packager && \
  lsb_release -r | awk {'print $2'} | sed -e 's/n\/a/unstable/g' > /build/distro_version && \
  echo /build && \
  ls -al /build && \
  echo build root contents && \
  find /build/root


default_install_commands: 

default_rpm_package:
  - FROM cdrx/fpm-ubuntu:18.04 as stage-package
  - RUN apt-get update && apt-get -y install rpm vim 
  - COPY --from=stage1 /build /build
  - |
      RUN mkdir /pkg && \
      DISTRO=$(cat /build/distro) && \
      DISTRO_VERSION=$(cat /build/distro_version) && \
      cd /pkg && \
      fpm -t rpm \
      -n unsafeopenssl \
      -v 0.1 \
      -m "<an@zeppelinen.com>" \
      --provides "unsafeopenssl" \
      --description "Unsafe version of OpenSSL 1.0.2i.\nDependency for qsslcaudit tool." \
      --url "https://github.com" \
      --iteration "${DISTRO}.${DISTRO_VERSION}" \
      -a "x86_64" \
      -C /build/root \
      -s dir ./

default_deb_package:
  - FROM cdrx/fpm-ubuntu:18.04 as stage-package
  - RUN apt-get update && apt-get -y install rpm vim 
  - COPY --from=stage1 /build /build
  - |
      RUN mkdir /pkg && \
      DISTRO=$(cat /build/distro) && \
      DISTRO_VERSION=$(cat /build/distro_version) && \
      cd /pkg && \
      fpm -t deb \
      -n unsafeopenssl \
      -v 0.1 \
      -m "<an@zeppelinen.com>" \
      --provides "unsafeopenssl" \
      --description "Unsafe version of OpenSSL 1.0.2i.\nDependency for qsslcaudit tool." \
      --url "https://github.com" \
      --iteration "${DISTRO}.${DISTRO_VERSION}" \
      -a "x86_64" \
      -C /build/root \
      -s dir ./

default_centos_commands:
  pre_build_commands:
    - |
      RUN yum -y update && \
      yum -y install epel-release && \
      yum -y install make glibc-devel gcc gcc-c++ zlib-devel zlib perl bzip2 redhat-lsb
  build_commands:
    - "{{ default_build_command }}"
  post_build_commands: "{{ default_rpm_package }}"

  install_dep_commands:

default_fedora_commands:
  pre_build_commands:
    - |
      RUN dnf -y update && \
      dnf -y install make gcc perl zlib-devel zlib bzip2 redhat-lsb
  build_commands:
    - "{{ default_build_command }}"
  post_build_commands: "{{ default_rpm_package }}"
  install_dep_commands:

default_debian_commands:
  pre_build_commands:
    - RUN apt-get update && apt-get -y install make gcc zlib1g zlib1g-dev bzip2 perl perl-base lsb-release
  build_commands:
    - "{{ default_build_command }}"
  post_build_commands: "{{ default_deb_package }}"

default_ubuntu_commands:
  pre_build_commands:
    - RUN apt-get update && apt-get -y install make gcc zlib1g-dev zlib1g bzip2 perl lsb-release
  build_commands:
    - "{{ default_build_command }}"
  post_build_commands: "{{ default_deb_package }}"

default_alt_commands:
  pre_build_commands:
    - RUN apt-get update && apt-get -y install make gcc zlib-devel zlib lsb-release
  build_commands:
    - "{{ default_build_command }}"
  post_build_commands: "{{ default_rpm_package }}"

platforms:
  - name: centos
    base_repo: centos
    versions:
      # - name: 5
      #   commands: "{{ default_centos_commands }}"
      - name: 6
        commands:
         pre_build_commands:
           - |
             RUN yum -y update && \
             yum -y install epel-release && \
             yum -y install make glibc-devel gcc gcc-c++ zlib-devel zlib perl bzip2 redhat-lsb
         build_commands:
           - RUN find . -type f -print0 | xargs -0 sed -i -e "s/secure_getenv/getenv/g"
           - "{{ default_build_command }}"
         post_build_commands: "{{ default_rpm_package }}"
         install_dep_commands:
      - name: 7
        commands: "{{ default_centos_commands }}"
  - name: fedora
    base_repo: fedora
    versions:
      - name: 28
        commands: "{{ default_fedora_commands }}"
      - name: 29
        commands: "{{ default_fedora_commands }}"
      - name: 30
        commands: "{{ default_fedora_commands }}"
  - name: ubuntu
    base_repo: ubuntu
    versions:
      # - name: lucid
      #   commands: "{{ default_ubuntu_commands }}"
      - name: precise
        commands:
          pre_build_commands:
            - RUN echo 'deb http://http.debian.net/debian wheezy-backports main' > /etc/apt/sources.list.d/wheezy-backports.list
            - RUN apt-get update && apt-get -y install make gcc zlib1g zlib1g-dev bzip2 perl lsb-release
          build_commands:
            - RUN find . -type f -print0 | xargs -0 sed -i -e "s/secure_getenv/getenv/g"
            - "{{ default_build_command }}"
          post_build_commands: "{{ default_deb_package }}"
      - name: trusty
        commands: "{{ default_ubuntu_commands }}"
      - name: xenial
        commands: "{{ default_ubuntu_commands }}"
      - name: bionic
        commands:
            pre_build_commands:
              - RUN apt-get update && apt-get -y install make gcc zlib1g zlib1g-dev bzip2 perl lsb-release
            build_commands:
              - "{{ default_build_command }}"
            post_build_commands: "{{ default_deb_package }}"
  - name: debian
    base_repo: debian
    versions:
      # - name: squeeze
      #   commands: "{{ default_debian_commands }}"
      - name: wheezy
        commands:
          pre_build_commands:
            - RUN echo 'deb http://http.debian.net/debian wheezy-backports main' > /etc/apt/sources.list.d/wheezy-backports.list
            - RUN apt-get update && apt-get -y install make gcc zlib1g zlib1g-dev bzip2 perl lsb-release
          build_commands:
            - RUN find . -type f -print0 | xargs -0 sed -i -e "s/secure_getenv/getenv/g"
            - "{{ default_build_command }}"
          post_build_commands: "{{ default_deb_package }}"
      - name: stretch
        commands: "{{ default_debian_commands }}"
  - name: mint
    base_repo: vcatechnology/linux-mint
    versions:
      - name: 18
        commands: "{{ default_ubuntu_commands }}"
      - name: 17
        commands: "{{ default_ubuntu_commands }}"
  - name: kalilinux
    base_repo: kalilinux/kali-linux-docker
    versions:
      - name: latest
        commands: "{{ default_debian_commands }}"
  - name: alt
    base_repo: alt
    versions:
      - name: sisyphus
        commands: "{{ default_alt_commands }}"
      # - name: p8
      #   commands: "{{ default_alt_commands }}"
  # - name: opensuse
  #   base_repo: opensuse
  #   versions:
  #     - name: tumbleweed
  #       commands: "{{ default_centos_commands }}"
  #     - name: leap
  #       commands: "{{ default_centos_commands }}"
  #     - name: harlequin
  #       commands: "{{ default_centos_commands }}"
